dist: trusty
sudo: required
language: c++

before_install:
  # Install llvm
  - sudo apt-add-repository 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty main'
  - sudo apt-add-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'
  - sudo apt-get -qq update
  - sudo apt-get install -y --allow-unauthenticated libstdc++-6-dev lcov
  - sudo apt-get install -y --allow-unauthenticated clang-4.0 clang-4.0-doc libclang-common-4.0-dev libclang-4.0-dev libclang1-4.0 libclang1-4.0-dbg libllvm-4.0-ocaml-dev libllvm4.0 libllvm4.0-dbg lldb-4.0 llvm-4.0 llvm-4.0-dev llvm-4.0-doc llvm-4.0-examples llvm-4.0-runtime clang-format-4.0 python-clang-4.0 libfuzzer-4.0-dev

script:
  # run tests and generate coverage files
  - bash gen_coverage.sh

after_success:
  # Uploading report to CodeCov
  - cd ${TRAVIS_BUILD_DIR}
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"