dist: trusty
sudo: required
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - cmake
            - libstdc++-7-dev 
            - lcov
      env:
         - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
            - libstdc++-7-dev 
            - lcov
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

script:
    # Print dir
    - ls -a
    # run tests and generate coverage files
    - bash gen_coverage.sh

after_success:
    # Uploading report to CodeCov
    - cd ${TRAVIS_BUILD_DIR}
    - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"